Update README.md
Ileriayo/markdown-badges pull request #341
Opened 2022-03-08 21:52 UTC by Artymanprince

2022-03-08 21:55 UTC, Artymanprince commented
This PR is based on the Badge Request made in issue #335.

2022-03-11 15:06 UTC, mehtaAnsh commented
@Ileriayo should we add badges these long? This will completely disturb our interface. Let me know

@Artymanprince thanks for your contribution :D

2022-03-19 08:19 UTC, Ileriayo commented
@Artymanprince, we need a more optimized badge URL.

2022-03-19 08:20 UTC, Ileriayo requested changes

2022-03-19 08:20 UTC, Ileriayo commented on README.md
> +| The Odin Project | ![The Odin Project](https://img.shields.io/badge/The%20Odin%20Project-D6AA68?style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAAM1BMVE
URL is too long

2022-09-03 22:05 UTC, kohasummons commented
I am closing this PR and Opening an Issue for the badge In question. Thanks everyone for the comments and participation. 

Issue: #432

2022-09-03 22:05 UTC, closed without merging