Adding SQL badge to languages section
Ileriayo/markdown-badges pull request #342
Opened 2022-03-13 06:59 UTC by frivajica

I added a SQL badge. As there wasn't any appropriate database icon available in simple-icons I had to use base64.

2022-03-19 08:22 UTC, Ileriayo requested changes

2022-03-19 08:22 UTC, Ileriayo commented on README.md
> +| SQL           | ![SQL](https://img.shields.io/badge/SQL-%23e0761f?style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjUyIiBoZWlnaHQ9IjMxNyIgdmlld0JveD0iMCAwIDI1MiAzMTciIGZpbGw9Im5v
Hey @frivajica!
Thanks for taking the time to contribute.
This URL is too long, can we get something shorter?

2022-05-08 04:52 UTC, taleroangel commented
Please add this one! is pretty cool!

2022-09-03 22:11 UTC, kohasummons commented
Heyy everyone participation in this discussion. I am closing this PR now and opening an Issue for whoever wants to pick this up in the future. Thanks for your ideas and contributions.

Issue: #433

2022-09-03 22:11 UTC, closed without merging