Updated the Readme and Added Terminal Category .
Ileriayo/markdown-badges pull request #607
Opened 2023-09-06 07:40 UTC by MunawarJohar

Please add my contribution

2023-09-06 07:41 UTC, MunawarJohar commented
Updated  the readme file and added terminal category.
Please merge my contribution.
Thank You

2023-09-06 07:44 UTC, kohasummons commented
No problemo @MunawarJohar, will review and merge when I have bandwidth.

2024-10-14 00:23 UTC, Ileriayo requested changes
Resolve merge conflicts.

2025-11-23 08:18 UTC, closed without merging

2025-11-23 08:18 UTC, Jukelyn commented
This PR is still touching too many unrelated lines for some reason. I'll just close this and open another PR for terminals.