Added EJS badge
Ileriayo/markdown-badges pull request #712
Opened 2024-05-22 18:13 UTC by josejefferson

## Description
[EJS (Embedded JavaScript templates)](https://ejs.co/) is a templating engine for generating HTML markup with plain JavaScript.

## Info

|Name|Category|Background Color|Logo Color|
|:--:|:--:|:--:|:--:|
EJS|Frameworks, Platforms and Libraries| `#B4CA65`|`#000000`

## Preview

| Badge | url |
| ----- | --- |
| ![EJS](https://img.shields.io/badge/ejs-%23B4CA65.svg?style=for-the-badge&logo=ejs&logoColor=black) | `![EJS](https://img.shields.io/badge/ejs-%23B4CA65.svg?style=for-the-badge&logo=ejs&logoColor=black)` |

2024-08-26 21:28 UTC, 3z3qu13l commented
lgtm

2024-10-14 00:53 UTC, Ileriayo requested changes
Resolve merge conflicts.

2024-10-14 21:33 UTC, josejefferson reviewed
Resolved

2024-10-15 00:04 UTC, Ileriayo approved these changes

2024-10-15 00:04 UTC, merged