README.md little misspelling error removed
Ileriayo/markdown-badges pull request #82
Opened 2021-04-20 22:18 UTC by Youngermaster

The Raspberry Pi Badge has an additional text, this one -> " />

Before

<img alt="Raspberry Pi" src="https://img.shields.io/badge/-Raspberry%20Pi-C51A4A?style=for-the-badge&logo=Raspberry-Pi"/>" />

After

<img alt="Raspberry Pi" src="https://img.shields.io/badge/-Raspberry%20Pi-C51A4A?style=for-the-badge&logo=Raspberry-Pi"/>

2021-04-28 16:00 UTC, mehtaAnsh approved these changes

2021-04-28 16:02 UTC, mehtaAnsh requested changes
Hey @Youngermaster , can you remove the `/>` in the markdown section of Raspberry PI and push it again? Thanks for contributing.

2021-04-29 01:58 UTC, Youngermaster commented
That's it, I know is something simple, but I wanted to contribute at least a little bit to the project 😅

@mehtaAnsh  Right now is giving this "*conflict*"
![image](https://user-images.githubusercontent.com/36933318/116493303-0cceaf80-a864-11eb-92c9-80a6f6b22019.png)

But as you can see, the only "*conflict*" is the extra `close tag` that I deleted
![image](https://user-images.githubusercontent.com/36933318/116493408-4ef7f100-a864-11eb-919f-b1b0d74fdff8.png)

2021-05-20 12:40 UTC, mehtaAnsh approved these changes

2021-05-20 12:41 UTC, merged